"""change box column names

Revision ID: aaea9ed1df44
Revises: e36675142335
Create Date: 2018-12-13 08:29:03.313823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aaea9ed1df44"
down_revision = "e36675142335"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("config", "in_use", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("config", "reserved", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_constraint("config_name_key", "config", type_="unique")
    op.add_column("box", sa.Column("job_id", sa.String(length=64), nullable=True))
    op.add_column("box", sa.Column("ssh_port", sa.Integer(), nullable=True))
    op.alter_column(
        "box", "port", existing_type=sa.VARCHAR(length=16), nullable=True
    )
    op.alter_column("box", "config_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("box", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_index("ix_box_id", table_name="box")
    op.drop_constraint("box_config_id_key", "box", type_="unique")
    op.drop_column("box", "box_connection_port")
    op.drop_column("box", "box_ssh_port")
    op.drop_column("box", "box_server")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "box",
        sa.Column(
            "box_server", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "box",
        sa.Column("box_ssh_port", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "box",
        sa.Column(
            "box_connection_port", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_unique_constraint("box_config_id_key", "box", ["config_id"])
    op.create_index("ix_box_id", "box", ["id"], unique=True)
    op.alter_column("box", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "box", "config_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "box", "port", existing_type=sa.VARCHAR(length=16), nullable=False
    )
    op.drop_column("box", "ssh_port")
    op.drop_column("box", "job_id")
    op.create_unique_constraint("config_name_key", "config", ["name"])
    op.alter_column("config", "reserved", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("config", "in_use", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###
